# Generated by Django 6.1.1 on 2026-09-21 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='pokemon_song',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
