# Generated by Django 6.1.1 on 2026-09-22 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_alter_journalentry_pokemon_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
